### ISSUE TITLE
Support different versions of Lock

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/auth0-sharepoint#3]
The authentication provider script should support different Login pages. It's currently downloading the login page from the CDN: https://github.com/auth0/auth0-sharepoint/blob/master/auth0-authentication-provider/auth0.psm1#L5

Ideally we should have 1 login page for every Lock release, and extend `auth0.psm1` to allow user input:

```
Enable-Auth0 -loginpage:v9 ... (which will download it from https://cdn.auth0.com/sharepoint/login-9.aspx)

Enable-Auth0 -loginpage:v10 ... (which will download it from https://cdn.auth0.com/sharepoint/login-10.aspx)
```

If the `loginpage` option is not specified, we should just download it from `https://cdn.auth0.com/sharepoint/login.aspx

**Comment by aaguiarz** [comment]
We'll be using the Auth0 login page moving forward.
