### ISSUE TITLE
Auth0 Roadmap and Deprecations for 2018: Introducing Lock 11. Deprecating Lock 7, 8, 9 and 10

### ISSUE THREAD

**Issue by maeni70** [auth0/auth0-sharepoint#5]
It seems that Lock <=10 will be deprecated April 1, 2018.

From Auth0:
**Introducing Lock 11. Deprecating Lock 7, 8, 9 and 10**
We’re continually improving the security of our service. As part of this, we are deprecating a set of APIs (usernamepassword/login, /ssodata, /tokeninfo, /delegation) used by Lock.js 7, 8, 9 and 10 and and auth0.js, 6, 7, 8. If you’re currently using our Hosted Login Page, no action is needed from you. Otherwise, if you embed Lock or auth0.js in your applications you should update them by April 1, 2018.

Has anybody been working on this?

**Comment by maeni70** [comment]
Attached login form compatible to Lock 10. I have used it as a template for our own, custom login form with Lock 11. It might work by just replacing path to Lock 11.

Sorry that I just provide it like this, but I am not an expert with projects in Github.

[login_lock10.zip](https://github.com/auth0/auth0-sharepoint/files/1686620/login_lock10.zip)

**Comment by aaguiarz** [comment]
There's a PR we'll be releasing soon here https://github.com/auth0/auth0-sharepoint/pull/6.

**Comment by aaguiarz** [comment]
We released a new version that redirects to the Auth0 Login page, https://github.com/auth0/auth0-sharepoint/pull/6
